#pragma once

// From glfw3.h
#define REMC_MOUSE_BUTTON_1         0
#define REMC_MOUSE_BUTTON_2         1
#define REMC_MOUSE_BUTTON_3         2
#define REMC_MOUSE_BUTTON_4         3
#define REMC_MOUSE_BUTTON_5         4
#define REMC_MOUSE_BUTTON_6         5
#define REMC_MOUSE_BUTTON_7         6
#define REMC_MOUSE_BUTTON_8         7
#define REMC_MOUSE_BUTTON_LAST      REMC_MOUSE_BUTTON_8
#define REMC_MOUSE_BUTTON_LEFT      REMC_MOUSE_BUTTON_1
#define REMC_MOUSE_BUTTON_RIGHT     REMC_MOUSE_BUTTON_2
#define REMC_MOUSE_BUTTON_MIDDLE    REMC_MOUSE_BUTTON_3